### ISSUE TITLE
unassert CLI tool

### ISSUE THREAD

**Issue by laco0416** [twada/unassert#5]
Hi.  Are you planning to provide a CLI? I'd like to use unassert easily without preprocessors like babel, browserify.

e.g. 

`$ unassert input.js > output.js `

(But I know also that I can do this by writing a script for this.)

**Comment by twada** [comment]
@laco0416 Nice idea! I'll create `unassert-cli` ASAP.

**Comment by laco0416** [comment]
@twada Great! I look forward to it! :smile:

**Comment by twada** [comment]
@laco0416 [unassert-cli](https://github.com/twada/unassert-cli) begins!

**Comment by twada** [comment]
Will be released soon.

**Comment by twada** [comment]
Just released [unassert-cli](https://www.npmjs.com/package/unassert-cli). Thank you for your request!

**Comment by laco0416** [comment]
Thank you very much!
